[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# PTSEFormer代码结构

## datasets<br/>数据集

## experiments<br/>实验配置文件和权重文件

## src

### configs

#### default\.py<br/>默认配置文件

### engine

#### engine\.py<br/>训练流程等

### models

#### backbone<br/>骨干网络

##### backbone\.py<br/>position\_encoding\.py

#### detr\_util<br/>DETR工具包

##### detr\_util\.py<br/>segmentation\.py

#### matcher<br/>计算匹配损失等

##### matcher\.py

#### ops<br/>注意力相关

##### functions<br/>modules

#### transformer<br/>相关的各种模型

##### attention\.py<br/>deformable\_transformer\.py

#### model\_builder\.py<br/>构建模型

## tools

### train\.py<br/>训练入口

### test\.py<br/>测试入口

## util<br/>图片处理工具和打印工具

## work\_dirs<br/>自定义的工作目录
