@startuml
'https://plantuml.com/sequence-diagram

autonumber

'第一阶段
activate PTSEFormer.forword
PTSEFormer.forword -> TrackDataPreprocessor: 数据集
note left #FFBBBB: 1st_stage
activate PTSEFormer.forword #FFBBBB
activate TrackDataPreprocessor
PTSEFormer.forword <- TrackDataPreprocessor: 用于视频目标检测的数据集，dataloader
deactivate TrackDataPreprocessor
PTSEFormer.forword -> backbone_and_neck: dataloader
activate backbone_and_neck
PTSEFormer.forword <- backbone_and_neck: 经过resnet和neck得到的特征图
deactivate backbone_and_neck
PTSEFormer.forword -> DeformableTransformerEncoder: 特征图
activate DeformableTransformerEncoder
PTSEFormer.forword <- DeformableTransformerEncoder: 编码后的特征图M_t和M_t+i，即图中的梯形蓝色框
deactivate DeformableTransformerEncoder
deactivate PTSEFormer.forword

'第二阶段
PTSEFormer.forword -> OursDecoderV2: 参考帧经过编码后的特征图M_t+i
note left #F1BCCB: 2nd_stage
activate PTSEFormer.forword #F1BCCB
activate OursDecoderV2
PTSEFormer.forword <- OursDecoderV2: 经过SATM后的特征f_t，即中间下方的绿色框
deactivate OursDecoderV2
PTSEFormer.forword -> SimpleDecoderV2: 关键帧经过编码后的特征图M_t
activate SimpleDecoderV2
PTSEFormer.forword <- SimpleDecoderV2: 经过TFAM后的特征h_t，即中间上方的第一个黄色框。
deactivate SimpleDecoderV2
deactivate PTSEFormer.forword

'第三阶段
PTSEFormer.forword -> SimpleDecoderV2: 特征h_t和f_t
activate PTSEFormer.forword #FF888B
note left #FF888B: 3rd_stage
activate SimpleDecoderV2
PTSEFormer.forword <- SimpleDecoderV2: 增强后的特征E_t
deactivate SimpleDecoderV2
deactivate PTSEFormer.forword

'第四阶段
PTSEFormer.forword -> OursDecoderV2: 第一阶段的M_t和特征E_t
activate PTSEFormer.forword #FEEEEB
note left #FEEEEB: 4th_stage
activate OursDecoderV2
PTSEFormer.forword <- OursDecoderV2: 增强后特征R_t
deactivate OursDecoderV2
deactivate PTSEFormer.forword

'第五阶段
PTSEFormer.forword -> QAM: 参考帧的特征f_t
activate PTSEFormer.forword #EEEEEE
note left #EEEEEE: 5th_stage
activate QAM
PTSEFormer.forword <- QAM: 聚合参考帧的目标查询
deactivate QAM
deactivate PTSEFormer.forword

'最终阶段
PTSEFormer.forword -> DeformableTransformerDecoder: 聚合参考帧的目标查询和增强后特征R_t
activate PTSEFormer.forword #FEEEBB
note left #FEEEBB: final_stage
activate DeformableTransformerDecoder
PTSEFormer.forword <- DeformableTransformerDecoder: 检测结果：类别和边界框
deactivate DeformableTransformerDecoder
deactivate PTSEFormer.forword

deactivate PTSEFormer.forword

@enduml